pipeline{
    agent any
    
    parameters{
        booleanParam(name: 'booleanTest', defaultValue: false)
    }
    stages{
        stage("Demo"){
            steps{
                echo "booleanParams set to : ${params.booleanTest}"
            }
        }
    }
}